### PR TITLE
AMD support

### PR DESCRIPTION
**Pull request by Rich-Harris**
This PR makes it possible to use Parallel with AMD loaders like Require.js.

### CODE REVIEW

**Comment by antoniopuero** [comment]
+1

**Comment by MaXwellFalstein** [comment]
Hi, a few of the members of this repo are working on [Parallel2.js](https://github.com/MaXwellFalstein/Parallel2.js). Would you like to resubmit this pull request to that repository?

If not, we can add this feature ourselves.

**Comment by Rich-Harris** [comment]
Hi – this isn't something I need any more, as AMD is ancient history. [It's all about ES modules now](http://rollupjs.org) :)

**Comment by MaXwellFalstein** [comment]
That is true to some extent. Okay, thanks for the update.

**Pull request closed without merging**
