### PR TITLE
Progress callbacks

### PR DESCRIPTION
**Pull request by blackrabbit99**
Add progress callbacks to ```map```  and ```reduce```

### CODE REVIEW

**Comment by amergin** [comment]
Interesting feature... Looking forward to it!

**Comment by mrunderhill89** [comment]
Another feature that would be nice is partial results, i.e. have a callback that receives each value returned by `map` as it's being calculated instead of waiting until `then` is called, so you could pass it to events, promises, or other asynchronous functions.

**Comment by mathiasrw** [comment]
@blackrabbit99 

any reason this was closed down?

**Comment by MaXFalstein** [comment]
@mathiasrw #96 supersedes this PR.

**Pull request closed without merging**
